// ─────────────────────────────────────────────────────────────
// Fall Hike App: the hike plan.
// This file is the single source of truth. Every fact the app shows,
// and every answer the Ask tab gives, comes from here.
// (The live-AI Worker in /phase2/ai-worker/ reads it too: redeploy it after edits.)
//
// After editing: bump VERSION in /sw.js so installed phones pick up the change.
// ─────────────────────────────────────────────────────────────

export const APP = {
  name: 'Fall Hike App',
  askPerson: 'Summan',
  // All five hikes fall in Eastern Daylight Time (DST ends Nov 1, 2026).
  tzOffset: '-04:00',
  timeZone: 'America/Toronto',
  // Home screen headline, intro and chips (over the photo).
  tagline: 'Five weekends. Five shades of fall.',
  intro: 'A low-pressure hiking plan for friends: easy-to-moderate routes, memorable views and a clear plan for five weekends in October.',
  chips: ['5 weekends', 'Easy → moderate', '45 min–1.5 hr from Toronto'],
  // Photos are from Wikimedia Commons under free licences; each is credited in the app.
  photo: {
    src: 'img/hikes/season.jpg',
    alt: 'Orange and red maples under a deep blue sky at Forks of the Credit',
    author: 'mark.watmough',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fall_2016_(30369753895).jpg',
  },
};

// General hiking basics shown on every hike's checklist.
// These are the only strings in the app that are not from the hike plan.
// Delete items here if you want the checklist to be plan-only.
export const BASICS = ['Water', 'Snacks', 'Layers', 'Sturdy shoes', 'Charged phone'];

// Kid-friendly sign on each hike (hike.kids), set from its difficulty:
// 'yes' = kid-friendly, 'easy-trail' = kid-friendly on the easy trail only, 'no' = not for kids.
export const KIDS_LABELS = { yes: 'Kid-friendly', 'easy-trail': 'Kid-friendly: easy trail', no: 'Not for kids' };

// Group rules and general tips for the Ask tab's quick answers.
// rain, carpool and kids are the organizer's rules. The rest is general
// advice, not from the hike plan: edit freely.
export const GROUP = {
  rain: `We still go in light rain, so bring a rain jacket. If the weather looks bad, ${APP.askPerson} will post any change in the group chat the night before.`,
  carpool: `Each hike page has a Rides list. Reply Coming, pick I can drive or Need a ride, and pick your area: riders see drivers from their area first. Tap Message to WhatsApp someone, or Ride with to save a seat in a driver's car; the seats left count down by themselves, and you can cancel your seat any time. Sharing your WhatsApp number is optional, and everything is deleted a week after the hike.`,
  kids: `Kids are welcome on the kid-friendly trails. Check each hike's difficulty and decide whether it suits your kids.`,
  swim: `No swimming on these hikes: they're group hikes, and the water is cold in October. Enjoy the rivers and falls from the trail.`,
  bikes: `Leave the bike at home: these are group hikes. Some of these parks allow bikes only on certain trails, so check the park's website before riding there another day.`,
  cell: `Signal is usually fine near the parking lots but can be patchy on the trails. This app works offline once it's installed. For directions with no signal, save the area in Google Maps for offline use before you leave.`,
  emergency: `In an emergency, call 911 right away. Then let ${APP.askPerson} and the group know where you are.`,
};

export const HIKES = [
  {
    id: 'forks-of-the-credit',
    n: 1,
    dateISO: '2026-10-03',
    day: 3,
    meetTime24: '08:00',
    dateShort: 'Sat Oct 3',
    dateLong: 'Saturday, October 3',
    park: 'Forks of the Credit Provincial Park',
    shortName: 'Forks of the Credit',
    area: 'Caledon',
    level: 'EASY',
    optionLevel: null,
    meet: {
      time: '8:00 AM',
      place: 'the park gate',
      address: '17760 McLaren Rd, Caledon',
      note: 'The gate opens at 8:00 sharp, no earlier.',
    },
    trails: [
      { name: 'Meadow Trail / Kettle Trail loop', level: 'EASY', length: null, time: null, note: 'Loop around Kettle Lake' },
    ],
    fallLine: 'Escarpment maples and Cataract Falls on an easy loop around Kettle Lake.',
    highlights: ['Escarpment maples', 'Cataract Falls', 'The loop around Kettle Lake'],
    drive: { text: '~55–70 min from North York', short: '~55–70 min' },
    fee: {
      amount: '~$18/vehicle',
      note: 'Every car needs an advance day-use permit.',
      short: 'advance day-use permit needed for every car',
    },
    booking: {
      url: 'https://reservations.ontarioparks.com',
      host: 'reservations.ontarioparks.com',
      label: 'Book day-use permit',
      cta: 'Book permit',
      required: true,
    },
    washrooms: 'Vault toilets',
    noWashrooms: false,
    dogs: 'Leashed dogs OK',
    picnic: 'Picnic tables',
    food: 'Belfountain village (about 5 min) or Erin (about 15 min)',
    kids: 'yes',
    kidsNote: null,
    alerts: [
      { kind: 'permit', title: 'Every car needs a permit', text: 'Book an advance day-use permit at reservations.ontarioparks.com (~$18/vehicle).' },
      { kind: 'time', title: 'Gate opens at 8:00 sharp', text: 'No earlier. We meet there at 8:00 AM.' },
    ],
    bring: ['Advance day-use permit for your car (~$18/vehicle)', 'Leash, if your dog is coming'],
    maps: 'Forks of the Credit Provincial Park, 17760 McLaren Rd, Caledon, ON L7K 2H8',
    backup: { name: 'Mono Cliffs Provincial Park', maps: 'Mono Cliffs Provincial Park, ON' },
    fallbackTrailheads: null,
    accent: 'rust',
    photo: {
      src: 'img/hikes/forks-of-the-credit.jpg',
      alt: 'Cataract Falls framed by red, orange and gold fall trees',
      author: 'mark.watmough',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
      source: 'https://commons.wikimedia.org/wiki/File:Fall_2016_(30369741725).jpg',
    },
  },
  {
    id: 'dundas-valley',
    n: 2,
    dateISO: '2026-10-11',
    day: 11,
    meetTime24: '08:30',
    dateShort: 'Sun Oct 11',
    dateLong: 'Sunday, October 11',
    // Moved from Saturday Oct 10 (Scout tells anyone who asks about Oct 10).
    movedFrom: { day: 10, dateShort: 'Sat Oct 10' },
    park: 'Dundas Valley Conservation Area',
    shortName: 'Dundas Valley',
    area: 'Dundas',
    level: 'EASY',
    optionLevel: 'MODERATE',
    meet: { time: '8:30 AM', place: 'the Trail Centre', address: '650 Governors Rd, Dundas', note: 'Now on Sunday, Oct 11 (moved from Saturday).' },
    trails: [
      { name: 'Main Loop Trail', level: 'EASY', length: '3.4 km', time: '~90 min', note: null },
      { name: 'Heritage Trail', level: 'MODERATE', length: '5 km', time: null, note: 'Moderate option' },
    ],
    fallLine: 'Old-growth forest and the Hermitage Ruins.',
    highlights: ['Old-growth forest', 'Hermitage Ruins'],
    drive: { text: '~75–90 min', short: '~75–90 min' },
    fee: {
      amount: '$11.50/vehicle',
      note: 'No reservation needed. You can buy the day pass online up to 5 days ahead (up to 6 people and 1 car per pass) and scan the barcode at the gate.',
      short: 'day pass online or on arrival',
    },
    booking: {
      url: 'https://conservationhamilton.ca/day-pass/',
      host: 'conservationhamilton.ca',
      label: 'Buy a Dundas Valley day pass',
      cta: 'Day pass',
      required: false,
    },
    washrooms: 'Washrooms at the Trail Centre',
    noWashrooms: false,
    dogs: 'Dogs OK',
    picnic: null,
    food: 'Downtown Dundas (about 10 min)',
    kids: 'yes',
    kidsNote: null,
    alerts: [
      { kind: 'time', title: 'Now on Sunday, Oct 11', text: 'Moved from Saturday Oct 10. Meet 8:30 AM at the Trail Centre.' },
      { kind: 'crowd', title: 'Thanksgiving weekend: extremely busy', text: 'Fallback trailheads: Headwaters, Monarch.' },
    ],
    bring: ['$11.50 per vehicle: a day pass bought online, or pay on arrival'],
    maps: 'Dundas Valley Conservation Area Trail Centre, 650 Governors Rd, Dundas, ON L9H 5E3',
    // Backup: Dundas Peak needs a reservation; Hilton Falls if it's sold out.
    backup: {
      name: 'Dundas Peak & Tew Falls, Dundas',
      maps: 'Dundas Peak and Tew Falls parking lot, 581 Harvest Rd, Dundas, ON',
      note: 'Reservation required from Sept 26 to Nov 8: no drive-up entry. Book a 2-hour Dundas Peak & Tew Falls slot, one car per booking. Bookings open 9 days ahead (Fri Oct 2) and close at midnight Sat Oct 10. $11 per car, $5.50 per passenger and a $10 booking fee. Park at 581 Harvest Rd; about 1.8 km to the peak and back.',
      booking: { url: 'https://conservationhamilton.ca/spencer-gorge-reservations/', host: 'conservationhamilton.ca', label: 'Reserve Dundas Peak' },
      then: { name: 'Hilton Falls, Milton', maps: 'Hilton Falls, Milton, ON' },
    },
    fallbackTrailheads: ['Headwaters', 'Monarch'],
    accent: 'forest',
    photo: {
      src: 'img/hikes/dundas-valley.jpg',
      alt: 'The stone Hermitage Ruins among fall trees',
      author: 'Jaydenfromcanada',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      source: 'https://commons.wikimedia.org/wiki/File:HamiltonHermitage.jpg',
    },
  },
  {
    id: 'rattlesnake-point',
    n: 3,
    dateISO: '2026-10-17',
    day: 17,
    meetTime24: '08:30',
    dateShort: 'Sat Oct 17',
    dateLong: 'Saturday, October 17',
    park: 'Rattlesnake Point Conservation Area',
    shortName: 'Rattlesnake Point',
    area: 'Milton',
    level: 'MODERATE',
    optionLevel: 'EASY',
    meet: { time: '8:30 AM', place: 'the gate', address: '7200 Appleby Line, Milton', note: 'The park opens at 8:30 AM.' },
    trails: [
      { name: 'Buffalo Crag Trail', level: 'MODERATE', length: '3 km', time: null, note: 'Escarpment-edge lookout over Nassagaweya Canyon' },
      { name: 'Vista Adventure Trail', level: 'EASY', length: '1.5 km', time: null, note: 'Easy option' },
    ],
    fallLine: 'An escarpment-edge lookout over Nassagaweya Canyon.',
    highlights: ['Escarpment-edge lookout over Nassagaweya Canyon'],
    drive: { text: '~45–60 min', short: '~45–60 min' },
    fee: {
      amount: '$10.50+HST/adult',
      note: 'Reservations recommended, not required: $10.50+HST per adult online at parkvisit.ca, or $12+HST at the gate. Kids 5–14 $7.25+HST online; under 5 free. One car per reservation.',
      short: 'reserve online at parkvisit.ca (recommended)',
    },
    booking: {
      url: 'https://parkvisit.ca',
      host: 'parkvisit.ca',
      label: 'Pay online at parkvisit.ca',
      cta: 'Pay online',
      required: false,
    },
    washrooms: null,
    noWashrooms: false,
    dogs: 'Dogs OK',
    picnic: null,
    food: 'Milton (about 15–20 min)',
    kids: 'easy-trail',
    kidsNote: 'Keep kids close at the cliff-edge lookouts.',
    alerts: [
      { kind: 'road', title: 'Appleby Line is CLOSED for construction', text: 'Detour: Derry Rd → Bell School Line → 14 Side Road (+15 min).' },
    ],
    bring: ['Online admission: $10.50+HST per adult', 'The detour: Derry Rd → Bell School Line → 14 Side Road'],
    maps: 'Rattlesnake Point Conservation Area, 7200 Appleby Line, Milton, ON L9E 0M9',
    backup: {
      name: 'Kelso, Milton',
      maps: 'Kelso Conservation Area, 5234 Kelso Rd, Milton, ON',
      note: 'Another Conservation Halton park: same fees, and it opens at 8:30 AM too.',
      booking: { url: 'https://parkvisit.ca', host: 'parkvisit.ca', label: 'Reserve Kelso at parkvisit.ca' },
    },
    fallbackTrailheads: null,
    accent: 'amber',
    photo: {
      src: 'img/hikes/rattlesnake-point.jpg',
      alt: 'Fall colours across Nassagaweya Canyon from the escarpment edge',
      author: 'jockrutherford',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      source: 'https://commons.wikimedia.org/wiki/File:Rattlesnake_Point_(45334957511).jpg',
    },
  },
  {
    id: 'crawford-lake',
    n: 4,
    dateISO: '2026-10-24',
    day: 24,
    meetTime24: '08:30',
    dateShort: 'Sat Oct 24',
    dateLong: 'Saturday, October 24',
    park: 'Crawford Lake Conservation Area',
    shortName: 'Crawford Lake',
    area: 'Milton',
    level: 'EASY',
    optionLevel: 'MODERATE',
    meet: { time: '8:30 AM', place: 'the gate', address: '3115 Conservation Rd, Milton', note: 'The park opens at 8:30 AM. The Longhouse Village and visitor centre open at 10:00 AM.' },
    trails: [
      { name: 'Crawford Lake Trail', level: 'EASY', length: '1.4 km', time: null, note: 'Boardwalk loop around the lake' },
      { name: 'Escarpment Trail', level: 'MODERATE', length: '~2 km', time: null, note: 'To the Nassagaweya Canyon lookout. Rocky and steep in places' },
    ],
    fallLine: 'A boardwalk loop around a rare, still lake, a reconstructed 15th-century longhouse village, and a lookout over Nassagaweya Canyon.',
    highlights: ['Boardwalk around Crawford Lake', 'Longhouse Village (opens 10 AM)', 'Nassagaweya Canyon lookout'],
    drive: { text: '~45–55 min from North York', short: '~45–55 min' },
    fee: {
      amount: '$10.50+HST/adult',
      note: 'Reservations recommended, not required: $10.50+HST per adult online at parkvisit.ca, or $12+HST at the gate. Kids 5–14 $7.25+HST online; under 5 free. One car per reservation.',
      short: 'reserve online at parkvisit.ca (recommended)',
    },
    booking: {
      url: 'https://parkvisit.ca',
      host: 'parkvisit.ca',
      label: 'Reserve at parkvisit.ca',
      cta: 'Reserve',
      required: false,
    },
    washrooms: null,
    noWashrooms: false,
    dogs: 'Leashed dogs OK (keep them out of the lake)',
    picnic: 'Picnic areas',
    food: 'Campbellville (about 5 min) or Milton (about 15 min)',
    kids: 'yes',
    kidsNote: 'The boardwalk is easy, but the way down to it is a steep, rocky slope: not for strollers.',
    alerts: [
      { kind: 'change', title: 'New park: replaces Balls Falls', text: 'Same date, Sat Oct 24. Meet 8:30 AM at the gate.' },
    ],
    bring: ['Online reservation from parkvisit.ca ($10.50+HST per adult, recommended)', 'Leash, if your dog is coming'],
    maps: 'Crawford Lake Conservation Area, 3115 Conservation Rd, Milton, ON',
    backup: {
      name: 'Hilton Falls, Milton',
      maps: 'Hilton Falls Conservation Area, 4985 Campbellville Rd, Milton, ON',
      note: 'Another Conservation Halton park: same fees, and it opens at 8:30 AM too.',
      booking: { url: 'https://parkvisit.ca', host: 'parkvisit.ca', label: 'Reserve Hilton Falls at parkvisit.ca' },
    },
    fallbackTrailheads: null,
    accent: 'falls',
    photo: {
      src: 'img/hikes/crawford-lake.jpg',
      alt: 'Golden fall maples against a blue sky at Crawford Lake',
      author: 'Angus Chan',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
      source: 'https://commons.wikimedia.org/wiki/File:CLCA_IMG_2444_(10283954034).jpg',
    },
  },
  {
    id: 'mount-nemo',
    n: 5,
    dateISO: '2026-10-31',
    day: 31,
    meetTime24: '08:30',
    dateShort: 'Sat Oct 31',
    dateLong: 'Saturday, October 31',
    park: 'Mount Nemo Conservation Area',
    shortName: 'Mount Nemo',
    area: 'Burlington',
    level: 'EASY',
    optionLevel: 'MODERATE',
    meet: { time: '8:30 AM', place: 'the main parking lot', address: '5317 Guelph Line, Burlington', note: 'The park opens at 8:30 AM.' },
    trails: [
      { name: 'South Loop Trail', level: 'EASY', length: '2.3 km', time: null, note: 'Crevices and small caves in the rock' },
      { name: 'North Loop + South Loop', level: 'MODERATE', length: '~5 km', time: null, note: 'Both loops along the escarpment edge (part of the Bruce Trail)' },
    ],
    fallLine: 'The Brock Harris Lookout: fall colours across the escarpment, and on a clear day the CN Tower in the distance.',
    highlights: ['Brock Harris Lookout', 'Crevices and small caves on the South Loop', 'Turkey vultures over the escarpment'],
    drive: { text: '~50–60 min from North York', short: '~50–60 min' },
    fee: {
      amount: '$10.50+HST/adult',
      note: 'Book online at parkvisit.ca before you go: $10.50+HST per adult ($12+HST at the gate). Kids 5–14 $7.25+HST online; under 5 free. One car per reservation.',
      short: 'book online at parkvisit.ca',
    },
    booking: {
      url: 'https://parkvisit.ca',
      host: 'parkvisit.ca',
      label: 'Reserve at parkvisit.ca',
      cta: 'Reserve',
      required: false,
    },
    washrooms: null,
    noWashrooms: false,
    dogs: 'Leashed dogs OK',
    picnic: 'Picnic areas',
    food: 'Burlington or Milton (about 15–20 min)',
    kids: 'yes',
    kidsNote: 'Keep kids back from the cliff edges at the lookout and around the crevices.',
    alerts: [
      { kind: 'change', title: 'New park: replaces Rouge Park', text: 'Same date, Sat Oct 31. Meet 8:30 AM at the main parking lot.' },
      { kind: 'permit', title: 'Book online before you go', text: 'Gate attendants aren\'t always on duty at Mount Nemo, so reserve at parkvisit.ca ($10.50+HST per adult). One car per reservation.' },
    ],
    bring: ['Online reservation from parkvisit.ca ($10.50+HST per adult)', 'Leash, if your dog is coming'],
    maps: 'Mount Nemo Conservation Area, 5317 Guelph Line, Burlington, ON',
    backup: {
      name: 'Kelso, Milton',
      maps: 'Kelso Conservation Area, 5234 Kelso Rd, Milton, ON',
      note: 'Another Conservation Halton park: same fees, and it opens at 8:30 AM too.',
      booking: { url: 'https://parkvisit.ca', host: 'parkvisit.ca', label: 'Reserve Kelso at parkvisit.ca' },
    },
    fallbackTrailheads: null,
    accent: 'dawn',
    photo: {
      src: 'img/hikes/mount-nemo.jpg',
      alt: 'Fall colours across farmland and forest below the escarpment at Mount Nemo',
      author: 'David Zhang from Canada',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      source: 'https://commons.wikimedia.org/wiki/File:Mount_Nemo_Conservation_Area_(50643563652).jpg',
    },
  },
];

export const hikeById = (id) => HIKES.find((h) => h.id === id) || null;
