// ─────────────────────────────────────────────────────────────
// Fall Hike App: the hike plan.
// This file is the single source of truth. Every fact the app shows,
// and every answer the Ask tab gives, comes from here.
//
// After editing: bump VERSION in /sw.js so installed phones pick up the change.
// ─────────────────────────────────────────────────────────────

export const APP = {
  name: 'Fall Hike App',
  askPerson: 'Summan',
  // All five hikes fall in Eastern Daylight Time (DST ends Nov 1, 2026).
  tzOffset: '-04:00',
  timeZone: 'America/Toronto',
};

// General hiking basics shown on every hike's checklist.
// These are the only strings in the app that are not from the hike plan.
// Delete items here if you want the checklist to be plan-only.
export const BASICS = ['Water', 'Snacks', 'Layers', 'Sturdy shoes', 'Charged phone'];

export const HIKES = [
  {
    id: 'forks-of-the-credit',
    n: 1,
    dateISO: '2026-10-03',
    day: 3,
    meetTime24: '08:00',
    dateShort: 'Sat Oct 3',
    dateLong: 'Saturday, October 3',
    park: 'Forks of the Credit Provincial Park',
    shortName: 'Forks of the Credit',
    area: 'Caledon',
    level: 'EASY',
    optionLevel: null,
    meet: {
      time: '8:00 AM',
      place: 'the park gate',
      note: 'The gate opens at 8:00 sharp, no earlier.',
    },
    trails: [
      { name: 'Meadow Trail / Kettle Trail loop', level: 'EASY', length: null, time: null, note: 'Loop around Kettle Lake' },
    ],
    fallLine: 'Escarpment maples and Cataract Falls on an easy loop around Kettle Lake.',
    highlights: ['Escarpment maples', 'Cataract Falls', 'The loop around Kettle Lake'],
    drive: { text: '~55–70 min from North York', short: '~55–70 min' },
    fee: {
      amount: '~$18/vehicle',
      note: 'Every car needs an advance day-use permit.',
      short: 'advance day-use permit needed for every car',
    },
    booking: {
      url: 'https://reservations.ontarioparks.com',
      host: 'reservations.ontarioparks.com',
      label: 'Book day-use permit',
      required: true,
    },
    washrooms: 'Vault toilets',
    noWashrooms: false,
    dogs: 'Leashed dogs OK',
    picnic: 'Picnic tables',
    alerts: [
      { kind: 'permit', title: 'Every car needs a permit', text: 'Book an advance day-use permit at reservations.ontarioparks.com (~$18/vehicle).' },
      { kind: 'time', title: 'Gate opens at 8:00 sharp', text: 'No earlier. We meet there at 8:00 AM.' },
    ],
    bring: ['Advance day-use permit for your car (~$18/vehicle)', 'Leash, if your dog is coming'],
    maps: 'Forks of the Credit Provincial Park, Caledon, ON',
    backup: { name: 'Mono Cliffs Provincial Park', maps: 'Mono Cliffs Provincial Park, ON' },
    fallbackTrailheads: null,
    accent: 'rust',
  },
  {
    id: 'dundas-valley',
    n: 2,
    dateISO: '2026-10-10',
    day: 10,
    meetTime24: '08:00',
    dateShort: 'Sat Oct 10',
    dateLong: 'Saturday, October 10',
    park: 'Dundas Valley Conservation Area',
    shortName: 'Dundas Valley',
    area: 'Dundas',
    level: 'EASY',
    optionLevel: 'MODERATE',
    meet: { time: '8:00 AM', place: 'the Trail Centre', note: null },
    trails: [
      { name: 'Main Loop Trail', level: 'EASY', length: '3.4 km', time: '~90 min', note: null },
      { name: 'Heritage Trail', level: 'MODERATE', length: '5 km', time: null, note: 'Moderate option' },
    ],
    fallLine: 'Old-growth forest and the Hermitage Ruins.',
    highlights: ['Old-growth forest', 'Hermitage Ruins'],
    drive: { text: '~75–90 min', short: '~75–90 min' },
    fee: {
      amount: '$11.50/vehicle',
      note: 'No reservation.',
      short: 'no reservation',
    },
    booking: null,
    washrooms: 'Washrooms at the Trail Centre',
    noWashrooms: false,
    dogs: 'Dogs OK',
    picnic: null,
    alerts: [
      { kind: 'crowd', title: 'Thanksgiving weekend: extremely busy', text: 'Fallback trailheads: Headwaters, Monarch.' },
    ],
    bring: ['$11.50 per vehicle for entry (no reservation)'],
    maps: 'Dundas Valley Conservation Area Trail Centre, Dundas, ON',
    backup: { name: 'Hilton Falls, Milton', maps: 'Hilton Falls, Milton, ON' },
    fallbackTrailheads: ['Headwaters', 'Monarch'],
    accent: 'forest',
  },
  {
    id: 'rattlesnake-point',
    n: 3,
    dateISO: '2026-10-17',
    day: 17,
    meetTime24: '08:30',
    dateShort: 'Sat Oct 17',
    dateLong: 'Saturday, October 17',
    park: 'Rattlesnake Point Conservation Area',
    shortName: 'Rattlesnake Point',
    area: 'Milton',
    level: 'MODERATE',
    optionLevel: 'EASY',
    meet: { time: '8:30 AM', place: 'the gate', note: null },
    trails: [
      { name: 'Buffalo Crag Trail', level: 'MODERATE', length: '3 km', time: null, note: 'Escarpment-edge lookout over Nassagaweya Canyon' },
      { name: 'Vista Adventure Trail', level: 'EASY', length: '1.5 km', time: null, note: 'Easy option' },
    ],
    fallLine: 'An escarpment-edge lookout over Nassagaweya Canyon.',
    highlights: ['Escarpment-edge lookout over Nassagaweya Canyon'],
    drive: { text: '~45–60 min', short: '~45–60 min' },
    fee: {
      amount: '$10.50+HST/adult',
      note: 'Pay online.',
      short: 'online',
    },
    booking: null,
    washrooms: null,
    noWashrooms: false,
    dogs: 'Dogs OK',
    picnic: null,
    alerts: [
      { kind: 'road', title: 'Appleby Line is CLOSED for construction', text: 'Detour: Derry Rd → Bell School Line → 14 Side Road (+15 min).' },
    ],
    bring: ['Online admission: $10.50+HST per adult', 'The detour: Derry Rd → Bell School Line → 14 Side Road'],
    maps: 'Rattlesnake Point Conservation Area, Milton, ON',
    backup: { name: 'Mount Nemo, Burlington', maps: 'Mount Nemo, Burlington, ON' },
    fallbackTrailheads: null,
    accent: 'amber',
  },
  {
    id: 'balls-falls',
    n: 4,
    dateISO: '2026-10-24',
    day: 24,
    meetTime24: '08:00',
    dateShort: 'Sat Oct 24',
    dateLong: 'Saturday, October 24',
    park: 'Balls Falls Conservation Area',
    shortName: 'Balls Falls',
    area: 'Jordan (Niagara)',
    level: 'EASY',
    optionLevel: null,
    meet: { time: '8:00 AM', place: 'the entrance', note: null },
    trails: [
      { name: 'Cataract Trail', level: 'EASY', length: '~3.4 km', time: null, note: 'Between the 11 m Upper Falls and the 27 m Lower Falls' },
    ],
    fallLine: 'Two waterfalls, the 11 m Upper Falls and the 27 m Lower Falls, plus the Glen Elgin heritage village.',
    highlights: ['11 m Upper Falls', '27 m Lower Falls', 'Glen Elgin heritage village'],
    drive: { text: '~1.25–1.5 hr', short: '~1.25–1.5 hr' },
    fee: {
      amount: '$15/vehicle',
      note: 'Passes at niagara.goingtocamp.com recommended.',
      short: 'pass at niagara.goingtocamp.com recommended',
    },
    booking: {
      url: 'https://niagara.goingtocamp.com',
      host: 'niagara.goingtocamp.com',
      label: 'Get a pass',
      required: false,
    },
    washrooms: null,
    noWashrooms: false,
    dogs: 'Dogs OK',
    picnic: null,
    alerts: [],
    bring: ['Pass from niagara.goingtocamp.com ($15/vehicle, recommended)'],
    maps: 'Balls Falls Conservation Area, Jordan, ON',
    backup: { name: 'Rock Point Provincial Park', maps: 'Rock Point Provincial Park, ON' },
    fallbackTrailheads: null,
    accent: 'falls',
  },
  {
    id: 'short-hills',
    n: 5,
    dateISO: '2026-10-31',
    day: 31,
    meetTime24: '07:30',
    dateShort: 'Sat Oct 31',
    dateLong: 'Saturday, October 31',
    park: 'Short Hills Provincial Park',
    shortName: 'Short Hills',
    area: 'St. Catharines',
    level: 'EASY',
    optionLevel: null,
    meet: { time: '7:30 AM', place: null, note: 'Sunrise opening, the only true early start.' },
    trails: [
      { name: 'Palaeozoic Path', level: 'EASY', length: '0.8 km', time: null, note: 'Barrier-free, to the Swayze Falls viewpoint' },
      { name: 'Scarlet Tanager Trail', level: 'EASY', length: '2.3 km', time: null, note: null },
    ],
    fallLine: 'A barrier-free path to the Swayze Falls viewpoint.',
    highlights: ['Swayze Falls viewpoint', 'Barrier-free Palaeozoic Path'],
    drive: { text: '~1.5–2 hr', short: '~1.5–2 hr' },
    fee: {
      amount: 'FREE',
      note: 'No booking.',
      short: 'no booking',
    },
    booking: null,
    washrooms: 'NO washrooms anywhere in the park',
    noWashrooms: true,
    dogs: null,
    picnic: null,
    alerts: [
      { kind: 'time', title: 'Meet 7:30 AM', text: 'Sunrise opening, the only true early start.' },
      { kind: 'washroom', title: 'NO washrooms anywhere in the park', text: 'Stop before you arrive.' },
      { kind: 'tick', title: 'Tick warning', text: 'Wear long pants and check yourself after.' },
    ],
    bring: ['Long pants (tick warning)', 'A washroom stop before you arrive (none in the park)', 'A tick check after the hike'],
    maps: 'Short Hills Provincial Park, St. Catharines, ON',
    backup: { name: 'Crawford Lake, Milton', maps: 'Crawford Lake, Milton, ON' },
    fallbackTrailheads: null,
    accent: 'dawn',
  },
];

export const hikeById = (id) => HIKES.find((h) => h.id === id) || null;
